### PR TITLE
Footer and links

### LINKED ISSUE #65: Simplified Footer
Let's have a cleaner footer like the one at https://toolkit.mozilla.org/.

### LINKED ISSUE #68: Links don't stand out enough
Since the most recent changes (but also before to some extent), there is not enough contract with the links styling for them to stand out. This leads to a poor user experience where people don't know where to click.

We'll need to come up with a better colour for links.

### PR DESCRIPTION
**Pull request by comzeradd**
* Fixes #65 
* Fixes #68

### CODE REVIEW

**Comment by comzeradd** [comment]
I adjusted the footer as discussed in the latest meeting.

I turned text links to bold, to make them more visible (see the roadmap link in the screenshot bellow). Another way would be to just underline them.

screen shot 2016-09-22 at 14 57 22

**Comment by brianking** [comment]
Where do those 4 links go to? I wonder if we can now get rid of the Follow and Subscribe sections on the main page now. It takes up a lot of real estate and doesn't add much value. We can at some stage replace it with a "news box" that posts updates about what is happening.

**Comment by comzeradd** [comment]
Yes, I though of that too. I don't know how much you want to emphasize these links.

So the Twitter link goes to MozParticpate account and the Chat goes to the Discourse category.

**Comment by nukeador** [comment]
Is "chat" the right word? Maybe it's better "Discussion"

**Comment by comzeradd** [comment]
Yes, good point. Here is a amended version.

screen shot 2016-09-22 at 16 52 28

**Comment by brianking** [comment]
Great. This looks good to go for me now.

**Comment by nukeador** [comment]
👍

**Pull request merged**
