### PR TITLE
Fix pt-BR file

### PR DESCRIPTION
**Pull request by mathjazz**
B0rken XML is b0rken.

### CODE REVIEW

**Comment by mathjazz** [comment]
For the sake of reference, this block #34.

**Comment by brianking** [comment]
Thanks Matjaž.

**Comment by comzeradd** [comment]
Probably a glitch on the quick and dirty script I wrote to prepopulate pt translations. Nothing to do with md2xliff, so this doesn't block the pontoon transition.

**Comment by MichaelKohler** [comment]
Great to hear, thanks for the investigation.

**Pull request merged**
