### PR TITLE
Update link

### PR DESCRIPTION
**Pull request by thingdiputra**

### CODE REVIEW

**Comment by berviantoleo** [comment]
I think you must squash your commit into one.

**Comment by jayvdb** [comment]
Yes, please squash them into one commit.

**Comment by MichaelKohler** [comment]
Thanks for the PR. As far as I know the xliff files are autogenerated. This would need to be changed in the .md files themselves. However I think this is fixed by https://github.com/mozilla/activate.mozilla.community/pull/123 . @comzeradd could you please close this one in favor of #123 ?

**Comment by comzeradd** [comment]
Yes, no need to edit `xliff` files directly.

**Pull request closed without merging**
