### PR TITLE
Added the feedback form link

### PR DESCRIPTION
**Pull request by dvigneshwer**
Added the https://mzl.la/howwasit link in the get feedback section.

### CODE REVIEW

**Comment by MichaelKohler** [comment]
Good idea! Thanks!

Would you mind changing the eventguide files in the pt/es subfolders as well?

**Comment by dvigneshwer** [comment]
Done with the previous [commit](https://github.com/mozilla/activate.mozilla.community/pull/236/commits/18c7d9796e9605a9008aba0451cae42a47a6037f)

Let me know in case of any other changes.

**Comment by MichaelKohler** [comment]
There is also pt-BR that needs this applied. Mind doing that as well? Then I'll merge this. Thanks a lot!

**Comment by dvigneshwer** [comment]
Completed with this [commit](https://github.com/mozilla/activate.mozilla.community/pull/236/commits/6389ac878bf078a9f66c17d635d418f5f9d6945a).

**Pull request merged**
