### PR TITLE
Support RTL Layouts, fixing #124

### PR DESCRIPTION
**Pull request by anefzaoui**
As issue #124 says, this would be the bedrock of having our RTL communities such as Urdu, Persian, Hebrew and Arabic contributing their localizations. Which when done would help more members from MENA to get involved easier with Activate Mozilla.

r?

### CODE REVIEW

**Comment by anefzaoui** [comment]
Also, #124 explains why this isn't a translation PR.

**Comment by anefzaoui** [comment]
Good catch! Thanks! Updating, with further changes.

**Comment by anefzaoui** [comment]
Updated.

**Comment by brianking** [comment]
Would also like @comzeradd to review this.

**Comment by anefzaoui** [comment]
How's this going?

**Comment by comzeradd** [comment]
Sorry for the delay. I'm just waiting for the Pontoon work to be completed before we do any more changes to the locales files.

**Comment by MichaelKohler** [comment]
Once the pontoon integration is done, we need to
1) make sure that the md files are up to date with the current version (since those are copies from the EN locale and we did some changes)
2) Inform the Pontoon team to include AR as well
3) Merge this request

**Comment by MichaelKohler** [comment]
I've just merged a PR which goes back to just having markdown files. Changes needed here:

* Please remove the xliff files again, we couldn't figure out a way to make this work as of now
* Please make sure that all ar/ markdown files are up to date with the English version. Please note that there are also new activities and therefore new md files in the root of the _pages folder.
* Please rebase your PR on top of the updated gh-pages branch to make sure we can get rid of the conflicts here.

Do you think you could do that? I'm sorry it took so long.

**Comment by MichaelKohler** [comment]
As we will be merging https://github.com/mozilla/activate.mozilla.community/pull/205 soon, I'm closing this PR, as this will require more work on the CSS side for supporting RTL layouts. Also the changes requested above need to be applied.

I'm sorry we couldn't merge this PR :(

**Pull request closed without merging**
