### PR TITLE
Retire e10s activity

### PR DESCRIPTION
**Pull request by comzeradd**

### CODE REVIEW

**Comment by comzeradd** [comment]
A first take on how we should showcase retired activites. I grayed out the activity box and added a label. On the Activity page I added a clear notice.

retired1

retired2

**Comment by nukeador** [comment]
Should we explain a bit more what "retired" means to be crystal clear we don't want people to do it?

**Comment by brianking** [comment]
Yes, let's explain it a bit more. I suggest something like:

"This activity is retired. What this means is that we don't recommend that you run the activity at this time and you will not receive any resources to do it."

Otherwise, looks great!

**Comment by comzeradd** [comment]
Great. I'm pushing the new text and adding this to all locales, before merging.

**Comment by nukeador** [comment]
"you will not receive any resources to do it" sounds a bit harsh here, I would suggest "resources will no longer be available"

**Pull request merged**
