### PR TITLE
Modify SUMO Sprint card

### PR DESCRIPTION
**Pull request by kelimuttu**
This is a modification for https://github.com/mozilla/activate.mozilla.community/issues/323

### CODE REVIEW

**Comment by kelimuttu** [comment]
Screenshot_2019-03-15 Welcome to Activate Mozilla(1)

Does this look ok @couci ?

**Comment by LucyeoH** [comment]
Also it should say "join the SUMO community BY supporting" not "through" supporting.

**Comment by MichaelKohler** [comment]
> Also it should say "join the SUMO community BY supporting" not "through" supporting.

Fixed and deploying..

**Comment by couci** [comment]
thanks @MichaelKohler all good now :)

**Pull request merged**
