### PR TITLE
[Fixes #92] Maker Party CTA

### LINKED ISSUE #92: Highlight Section on Homepage
We talked about adding a highlighted section on the homepage to bring attention to more urgent things. Some uses of it would be:
- To add a CTA for Maker Party
- Highlight time-bound activities
- Highlight activities that need more engagement

### PR DESCRIPTION
**Pull request by comzeradd**

### CODE REVIEW

**Comment by comzeradd** [comment]
Still in progress, but here are two screenshots for a Maker Party CTA

**Comment by nukeador** [comment]
The first one is good, but I'm not sure we want to focus that many attention to the CTA

**Comment by brianking** [comment]
I'm not a colours expert, so not sure which is the best. They both look of with me.

Can we make the MP logo smaller so that it doesn't take up so much vertical space?

**Comment by comzeradd** [comment]
Here is an example with a smaller logo. So the vertical space height is defined by the text.

**Comment by nukeador** [comment]
My worry is that we are taking most of top visible space of the frontpage with the image + CTA and people will need to scroll to check the 3 themes.

Maybe CTA would be better at the bottom?

**Comment by comzeradd** [comment]
Yes, that's a valid concern. Usually a CTA is meant to get the most attention, but we have it after the three activity categories.

Here is an example. I temporarily removed the language selector, to keep the bottom layout clean, and it can be moved on the footer bar as a dropdown (same as mozilla.org)

**Comment by nukeador** [comment]
I like it more now on the bottom. @brianking still not sure how "prominent" we want these CTAs and I guess that would affect the color scheme to use.

**Comment by brianking** [comment]
I like it below the activities for now as well. I wonder if highlighting the text more somehow (bolding or italic or darker colour) will make it more prominent?

**Comment by comzeradd** [comment]
We could slightly increase the font-size, to make it more visible but still keep it on 3 rows text on large screens.

I'd advice against using bold and italic won't help on readability.

**Comment by brianking** [comment]
Is this good to checkin?

**Comment by comzeradd** [comment]
Yeap. It's what you can see in the screenshot above. I just increased a bit the font-size on the CTA text.

**Comment by brianking** [comment]
Good to checkin.

**Comment by brianking** [comment]
I just spotted a typo!

"Help make a different ..." -> difference

Sorry if this is my mistake.

**Comment by comzeradd** [comment]
[Fixed](https://github.com/mozilla/activate.mozilla.community/commit/a64582499cfe9bbc366910bdee201656af0db1f5)

**Pull request merged**
