### PR TITLE
Updating links

### PR DESCRIPTION
**Pull request by ioana-chiorean**

### CODE REVIEW

**Comment by brianking** [comment]
@ioana-chiorean can you also fix them in the locales?

**Comment by ioana-chiorean** [comment]
sorry I missed this earlier @brianking 
I think it is now covered in #113

**Comment by MichaelKohler** [comment]
I agree with Ioana. @comzeradd could you please close this one in favor of #123 ?

**Comment by comzeradd** [comment]
Yes, I think the approach on Firefox links on #123 is more easy to maintain.

**Pull request closed without merging**
