### PR TITLE
fixed the broken UI issue on add-ons activity page

### PR DESCRIPTION
**Pull request by viswanathamsantosh**
addonfix

Looks like the UI is broken on add-ons activity page. Fixed it.

### CODE REVIEW

**Comment by viswanathamsantosh** [comment]
addonfixed
updated UI.

**Comment by MichaelKohler** [comment]
Oh, shoot. That's what I get from not testing it locally when merging PRs and I didn't see it in the previous PR while reviewing. Could you please do the same for the "localized" content in _pages/{es,pt-BR,id)? Thanks!

**Comment by viswanathamsantosh** [comment]
I got you covered! ;-) I'm on it.

**Comment by MichaelKohler** [comment]
Thanks a lot!

**Pull request merged**
