### PR TITLE
Revamp subpages

### PR DESCRIPTION
**Pull request by comzeradd**
* Add fixed TOC and back-to-top
* Change TOC colors to meet header's scheme
* Move all js files to the bottom
* Add animation to TOC links
* Add some space between chapters on long texts

### CODE REVIEW

**Comment by comzeradd** [comment]
I did some changes on the subpages (mostly on the activities pages). Tha lack of html on these pages limits the ability of doing massive changes, but at least I managed to do some basic stuff around the TOC, to help navigation, and the text.

I added just a small snippet on all long text pages to give some space between the chapters. I think I did the changes to all localized versions too, but it would be nice someone else gets another pass on this.



output

**Comment by nukeador** [comment]
This is cool.

I'm not really convinced by the dark blue background for the TOC

**Comment by brianking** [comment]
Approved ... checkin! Let's keep the colour for now and we can tweak later, at least it is consistent with the header.

**Comment by comzeradd** [comment]
Let's merge it and we can revisit later. I could try a lighter version of the TOC later.

**Pull request merged**
