### PR TITLE
First take on Leaderboard

### PR DESCRIPTION
**Pull request by comzeradd**

### CODE REVIEW

**Comment by comzeradd** [comment]
We can probably add more stuff when some changes happen on the API side, but as a first iteration I think it's a good start to have an overview of most active Mozillians.

screen shot 2016-11-21 at 10 51 37

**Comment by MichaelKohler** [comment]
LGTM!

**Comment by brianking** [comment]
LGTM as well!

**Comment by nukeador** [comment]
Is "No. of events" the right wording? Aren't we looking for "No. of activities" instead?

**Pull request merged**
