### PR TITLE
Revamp UI and responsiveness

### LINKED ISSUE #57: Site Issues in Responsive Mode
I see at least 3 issues

* [ ] Header navigation pushed the Mozilla link out of place. An ideal solution would be to have a hamburger menu
* [ ] Text starting 'Are you interested in other areas...' sits at the side, instead of underneath
* [ ] Blank section near the bottom

@comzeradd can you possibly help with this?

screen shot 2016-09-06 at 19 01 17
(first 2 issues illustrated)

screen shot 2016-09-06 at 19 01 29
(3rd issue illustrated)

### LINKED ISSUE #58: Align Design with New Clubs Site
My understanding is that the new Clubs site is being built on the same technology as the Activate site. I think it would make sense for them to have a similar design.

Can we share CSS, image assets, and perhaps even code or markup?

Bring in @comzeradd for initial comments on feasibility.

cc @LucyeoH and @bacharakis fyi.

### PR DESCRIPTION
**Pull request by comzeradd**
* Make better use of grid css classes
* Collapse navbar to a hamburger button for mobile
* Fix responsivness issues
* Removed unused html/css code
* Switch to Fira Sans
* Add basic branding graphics
* Add License
* Fixes #58 
* Fixes #57

### CODE REVIEW

**Comment by comzeradd** [comment]
@nukeador can you test it locally before we merge?

**Comment by nukeador** [comment]
* breadcumbs class is now too small
* Social icons to share don't have now a place to "hang from" since we removed the container side border
* Localized pages need class update too
* I'm not sure about this blue/purple colour for header, links. It's not very mozilla to me.

Cheers.

**Comment by comzeradd** [comment]
Thanks. I hadn't touch the subpages yet. I just amended the commit to address these issues.

Regarding the header, I followed the color scheme of the branding graphics created for the [stickers](https://github.com/mozilla/OpenDesign/issues/85) & [t-shirts](https://github.com/mozilla/OpenDesign/issues/86).

**Comment by nukeador** [comment]
If we want a dark blue colour we should check the sandstone palette

https://www.mozilla.org/en-US/styleguide/websites/sandstone/colors/

**Comment by nukeador** [comment]
I think #3F4B73 is way nicer for the dark blue

nightly-blue darkener 15% from https://mozilla.github.io/mofo-bootstrap/demo/

**Comment by comzeradd** [comment]
A screenshot with the `#3F4B73` version

screen shot 2016-09-19 at 11 20 01

**Comment by nukeador** [comment]
I still see this PR using the old colours. The rest seems to be fixed.

**Comment by comzeradd** [comment]
I just amended the commit with the new colors.

**Comment by nukeador** [comment]
Great work, look awesome, it's good to merge.

Question: I don really get what the favicon is :P

**Comment by comzeradd** [comment]
It's the rocket logo from the stickers design. But indeed it doesn't look that small. I reverted and we can revisit later.

**Comment by brianking** [comment]
Since the checkin, many pages on the site are redirecting to the mozilla.github.io version if the site, e.g. FAQ.

**Comment by umeshagarwal** [comment]
Just wanted to add my one cent to this work.. 
The "FAQ ROADMAP PARTICIPATION" on the top is little overlapping and has some rendering issue. 
It will be great if it looks more clear. 
I just visited all major sub links and it looks great to me!! 

screen shot 2016-09-19 at 11 06 11 pm

**Comment by nukeador** [comment]
@brianking that should be fixed by f692ffe373b731c120d8b76d44cf8ca4c0a7302b as soon as the cache is renewed

**Pull request merged**
