### PR TITLE
Little changes to the content

### PR DESCRIPTION
**Pull request by DineshMv**
1. Added 's' to matters in last line. - Rest of the changes can be compared.

### CODE REVIEW

**Comment by MichaelKohler** [comment]
Thanks for the PR. I think "matter" is actually correct, since it's plural. The rest looks good to me, but I've asked Caitlin to have a look as well to make sure she agrees as well.

**Comment by MichaelKohler** [comment]
Changes are approved by Caitlin. I'll comment in a few minutes with a small change request ;)

**Comment by DineshMv** [comment]
@MichaelKohler Submitted PR's for each page with the changes ignoring the word 'matter'. Is everything is good now?

**Comment by MichaelKohler** [comment]
Please change the "s" in this pull request as well and then we're set. You can just push a new commit here.

The other PRs look good and I'll merge them once I'm home.

**Pull request merged**
