### PR TITLE
[Fixes #56] Change Activity Categories

### LINKED ISSUE #56: Change Activity Categories
Talked to @LucyeoH about the possibility of aligning with the 3 big categories that will be used for the Mozilla Clubs site.

### PR DESCRIPTION
**Pull request by comzeradd**
This implements the categories change. On the frontpage we have the messages: Build, Teach, Protect the Web. All of those lead to an Activities page, with short description.

I'm attaching a couple of screenshots:

screen shot 2016-10-20 at 19 58 51

screen shot 2016-10-20 at 19 59 06

On the Activities page I just used the introductory text of each Activity, but we may want to adjust that.

### CODE REVIEW

**Comment by nukeador** [comment]
Aren't any icons on the frontpage for each category?

**Comment by nukeador** [comment]
Also, I think it would be more visual if each activity has also its icon.

**Comment by comzeradd** [comment]
Yes, we can add the graphics on frontpage too. Good thought. Bellow is a screenshot (not yet pushed).

On the activity page we can either have graphics for the categories or the activities. Having an icon/graphic on each paragraph is too much.

screen shot 2016-10-21 at 13 47 59

**Comment by brianking** [comment]
The lead in text for the activities are a bit abstract and don't fully say what is the task at hand. So here are my suggested wordings for each:

**e10s and Featured Add-ons**
With the emergence of multiprocess Firefox (e10s), we need to ensure featured add-ons on the Mozilla Add-ons site meet the highest levels of browser compatibility and functionality. Help us test these add-ons so that e10s can be rolled out to more of our millions of users.
[Find out more](/e10s-addons/).

**Install Test Pilot**
When building features for hundreds of millions of Firefox users worldwide, it’s important to get them right. Help us figure out which features should ship and how they should work. Install Test Pilot and give us feedback.
[Find out more](/test-pilot/).

**Dive Into Rust**
Rust is a systems programming language important to the future of the web. It runs blazingly fast, prevents segfaults, and guarantees thread safety. With your help, we want more developers to understand, use and evangelize this language in order to make the web better and more secure.
[Find out more](/rust-hack/).

**WebVR Camp**
A-Frame is a web framework for building virtual reality experiences, making it easy for anyone to get involved with virtual reality. Run events to onboard developers into 3D and write some great demos. This will advance WebVR, an open platform for virtual reality that leverages the Web.
[Find out more](/rust-hack/).

**Web Compatibility Sprint**
Web Compatibility, the ability for all Web content to run in all browsers, is important. There are multiple web content engines running on multiple devices, and sometimes with a little testing and some small tweaks to their site, developers can ensure that more users can have the full experience that is desired. Test sites and spread the message about compatibility.
[Find out more](/webcompat-sprint/).

**Comment by comzeradd** [comment]
I pushed the new texts. Are we good to merge?

**Comment by nukeador** [comment]
Yeah, let's merge and figure out how to keep improving the activities page.

**Pull request merged**
