### PR TITLE
Update to CPG Activate - Simplified & Added Telegram/Mozillians Chat

### PR DESCRIPTION
**Pull request by emmairwin**
Removed a lot of texts, simplified
added telegram/twitter chat for Thursday.

### CODE REVIEW

**Comment by MichaelKohler** [comment]
Looks good to me, did you inform the Spanish localizers of that change as well? Or will you point them to the updated page once merged?

Also, do you think it would be possible to include the changes to the pt/fr/es in this PR as well? You can basically copy/paste everything apart from the header information (with the lang: etc) since those are not localized yet.

**Comment by emmairwin** [comment]
I have not sent to localizers yet, I am wondering if it will frustrate them to do this now?  Or they will be OK with it?  @nukeador

**Comment by MichaelKohler** [comment]
Depends on how far they already are. As Jose knows about PRs, I think it would be fine to just point to this PR in a follow-up. 

I have a few minutes of free time, I'll take care of this :)

**Comment by emmairwin** [comment]
thank you I will do that

**Comment by MichaelKohler** [comment]
I'll follow up with another PR for the other locales.

**Pull request merged**
